create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports {CLK}]
set_property IOSTANDARD LVCMOS33 [get_ports {CLK}]
set_property PACKAGE_PIN E3 [get_ports {CLK}]

set_property PACKAGE_PIN C12 [get_ports SYS_NRST]
set_property IOSTANDARD LVCMOS33 [get_ports SYS_NRST]
set_property PULLUP true [get_ports SYS_NRST]

set_property PACKAGE_PIN C4 [get_ports UART_RXD]
set_property IOSTANDARD LVCMOS33 [get_ports UART_RXD]

set_property PACKAGE_PIN D4 [get_ports UART_TXD]
set_property IOSTANDARD LVCMOS33 [get_ports UART_TXD]
set_property DRIVE 8 [get_ports UART_TXD]
set_property SLEW FAST [get_ports UART_TXD]

set_property PACKAGE_PIN H17 [get_ports {LED[0]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}] 
set_property PACKAGE_PIN K15 [get_ports {LED[1]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}] 
set_property PACKAGE_PIN J13 [get_ports {LED[2]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}] 
set_property PACKAGE_PIN N14 [get_ports {LED[3]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}] 
set_property PACKAGE_PIN R18 [get_ports {LED[4]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}] 
set_property PACKAGE_PIN V17 [get_ports {LED[5]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}] 
set_property PACKAGE_PIN U17 [get_ports {LED[6]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}] 
set_property PACKAGE_PIN U16 [get_ports {LED[7]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
